import Head from "next/head";
import {
  AiFillLinkedin,
  AiFillInstagram,
  AiFillMail,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import profile from "../public/ferza.jpeg";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import eco1 from "../public/eco1.png";
import eco2 from "../public/eco2.png";
import risen1 from "../public/risen1.png";
import risen2 from "../public/risen2.png";
import risen3 from "../public/risen3.png";
import risen4 from "../public/risen4.png";
import bank1 from "../public/bank1.png";
import bank2 from "../public/bank2.png";
import bank3 from "../public/bank3.png";
import bank4 from "../public/bank4.png";
import bank5 from "../public/bank5.png";
import bank6 from "../public/bank6.png";
import bank7 from "../public/bank7.png";
import bank8 from "../public/bank8.png";
import bank9 from "../public/bank9.png";
import bank10 from "../public/bank10.png";
import bank11 from "../public/bank11.png";
import bank12 from "../public/bank12.png";
import bank13 from "../public/bank13.png";
import bank14 from "../public/bank14.png";
import bank15 from "../public/bank15.png";
import bank16 from "../public/bank16.png";
import bankmobile from "../public/bankmobile.png";
export default function Home() {
  const [darkMode, setDarkMode] = useState(true);
  const [openModal, setOpenModal] = useState(false);
  const [selectedProject, setSelectedProject] = useState(null);

  const projects = [
  {
    id: 1,
    title: "Eco-Motive (Figma)",
    images: [eco1, eco2], 
    description: `
Eco-Motive is an innovative mobile application that brings the zero-waste concept
to the workshop industry. Designed using Figma, Eco-Motive transforms how we view
workshop waste such as used tires and oil, turning them into useful resources.

Key Features:
• Access reusable workshop waste items  
• Find nearby workshops  
• Digital wallet top-up system  
• Supports sustainable environmental practices
`
  },
  {
    id: 2,
    title: "RisenMedic (Website Design)",
    images: [risen1, risen2, risen3, risen4], 
    description: `
RisenMedic is a healthcare website concept similar to HaloDoc, designed to make
health services more accessible.

Features include:
• Online doctor consultation  
• Emergency service access  
• Health news & articles  
• Clinic & pharmacy locator  
• Medicine availability & online orders
`
  },
  {
  id: 3,
  title: "Intern — PT. Bank NTB Syariah (IT Division)",
  images: [bank1, bank2, bank3, bank4, bank5, bank6, bank7, bank8, bank9, bank10, bank11, bank12, bank13, bank14, bank15, bank16, bankmobile], 
  description: `
During my internship at **PT. Bank NTB Syariah – Technology & System Integration Division**,  
I worked on several real industry tasks such as:

• creating a **Data Centre Visitor Access Request System (Web App)** using Laravel & PostgreSQL  
• configuring desktop PCs and bank-related applications  
• preparing IT environments for internal users  
• managing physical document archives  
• assisting internal IT support activities  

The website allows vendors & visitors to submit temporary access permission into the Bank's Data Centre, including identity verification, visit scheduling, and admin approval flow.

This project helped me improve:
✔ Backend & API development  
✔ Database design  
✔ System deployment workflow  
✔ Communication with IT staff & vendors  
✔ Real-world problem solving in banking industry
  `
}

];

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Fernanda Wawang Azraqi - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">Portfolio of Fernanda</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                href="https://drive.google.com/file/d/1O59yhVLhj06g_VUJ7UHpKxGfr2_9rWob/view?usp=sharing"
                target="_blank"
                rel="noopener noreferrer"
              >
                Resume
              </a>

              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Fernanda Wawang Azraqi
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Fullstack Web Developer & Designer.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
               Bachelor of Computer Science graduate with hands-on experience in
              fullstack web development and system analysis within a banking
              environment. Passionate about building reliable web applications
              using Laravel and PostgreSQL, supported by strong analytical and
              documentation skills.
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">

  {/* LinkedIn */}
  <a
    href="https://www.linkedin.com/in/fernanda-wawang-azraqi-383980225/"
    target="_blank"
    rel="noopener noreferrer"
  >
    <AiFillLinkedin className="cursor-pointer hover:text-teal-500 transition"/>
  </a>

  {/* Instagram */}
  <a
    href="https://www.instagram.com/ferzaa._"
    target="_blank"
    rel="noopener noreferrer"
  >
    <AiFillInstagram className="cursor-pointer hover:text-teal-500 transition"
 />
  </a>

 {/* Email */}
  <a href="mailto:fernandaazra@gmail.com">
    <AiFillMail className="cursor-pointer hover:text-teal-500 transition" />
  </a>

</div>

            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={profile} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">What I Do</h3>
<p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
  I am a Fullstack Web Developer with experience in building internal
  web applications using Laravel and PostgreSQL. My work mainly focuses
  on system analysis, translating business requirements into technical
  solutions, and ensuring structured and well–documented development.
</p>

<p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
  I also have experience in UI/UX design, graphic design, and digital
  content creation — supported by a strong background in Computer Science
  and Machine Learning fundamentals.
</p>


          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={design} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Beautiful Designs
              </h3>
             <p className="py-2">
  I design clean and structured interfaces for web systems and digital
  content, focusing on clarity, usability, and consistency.
</p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Canva</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">
  Fullstack Web Development
</h3>
<p className="py-2">
  I build web applications using Laravel and PostgreSQL — including
  authentication, structured data management, system workflows, and
  backend logic to support real business processes.
</p>
<h4 className="py-4 text-teal-600">Technologies I Use</h4>
<p className="text-gray-800 py-1">Laravel (PHP)</p>
<p className="text-gray-800 py-1">PostgreSQL</p>
<p className="text-gray-800 py-1">MySQL</p>
<p className="text-gray-800 py-1">HTML / CSS / JS</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={consulting} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">
  System Analysis & Documentation
</h3>
<p className="py-2">
  I analyse system needs, structure requirements, and create clear
  technical documentation to support development and IT operations,
  especially in multi–stakeholder environments such as banking.
</p>
<h4 className="py-4 text-teal-600">Focus Areas</h4>
<p className="text-gray-800 py-1">Requirement Gathering</p>
<p className="text-gray-800 py-1">Process Mapping</p>
<p className="text-gray-800 py-1">Technical Documentation</p>
<p className="text-gray-800 py-1">System Workflow Design</p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Portofolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
  I have hands–on experience developing internal web systems during
  my internship at PT Bank NTB Syariah, where I built a Data Access
  Form System used to manage vendor access requests and attendance
  workflows for IT infrastructure activities.
</p>

<p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
  My work focuses on building structured systems, ensuring data
  validation, documentation, and supporting daily IT operations
  through reliable web–based solutions.
</p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
  {projects.map(project => (
    <div
      key={project.id}
      className="basis-1/3 flex-1 cursor-pointer"
      onClick={() => {
        setSelectedProject(project);
        setOpenModal(true);
      }}
    >
      <Image
        className="rounded-lg object-cover"
        layout="responsive"
        width={800}
        height={450}
        src={project.images[0]}
      />

      <h4 className="text-lg mt-3 dark:text-white">
        {project.title}
      </h4>
    </div>
  ))}
</div>

        </section>
        {openModal && selectedProject && (
  <div className="fixed inset-0 bg-black bg-opacity-70 flex justify-center items-center z-50">
    <div className="bg-white dark:bg-gray-800 p-6 rounded-lg max-w-4xl w-11/12 max-h-[90vh] overflow-y-auto relative">

      {/* Close Button */}
      <button
        className="absolute top-3 right-3 text-xl text-gray-600"
        onClick={() => setOpenModal(false)}
      >
        ✕
      </button>

      {/* Title */}
      <h2 className="text-2xl font-bold mb-4 dark:text-white">
        {selectedProject.title}
      </h2>

      {/* Images */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-6">
  {selectedProject.images.map((img, index) => (
    <Image
      key={index}
      src={img}
      layout="responsive"
      width={800}
      height={450}
      className="rounded-lg object-cover"
    />
  ))}
</div>

      {/* Description */}
      <p className="text-gray-700 dark:text-gray-200 whitespace-pre-line">
        {selectedProject.description}
      </p>
    </div>
  </div>
)}

      </main>
    </div>
  );
}
